tag @s add fatal_damage_died
scoreboard players operation @a[scores={分队=1..4}] damage_uid.cache = @s fatal_damage_uid
execute @a[scores={分队=1..4}] ~~~ scoreboard players operation @s fatal_damage_uid -= @s damage_uid.cache
scoreboard players random @e[type=armor_stand,name=main] kill_tell_num 1 5
scoreboard players set @a[tag=fatal_damage_died] xp_cache 0
scoreboard players set @a[tag=fatal_damage_died] got_xp 0
scoreboard players set @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] xp_cache 0
scoreboard players set @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] got_xp 0
playsound random.orb @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}]
execute @e[type=armor_stand,name=main,scores={kill_tell_num=1}] ~~~ execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @a { "rawtext": [ { "translate": "%%5", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={分队=..1}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..2}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..3}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } }, { "selector": "@a[tag=fatal_damage_died]" }, {"translate":"text.tellraw.ingameinfo.kill_tell_num_1"}, { "translate": "%%5", "with": { "rawtext": [ { "selector": "@s[scores={分队=..1}]"}, { "selector": "@s[scores={分队=..2}]"}, { "selector": "@s[scores={分队=..3}]"}, { "selector": "@s[scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } },{ "selector": "@s" }, { "translate": "%%2", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={红床存活=0,分队=1}]" }, { "selector": "@a[tag=fatal_damage_died,scores={蓝床存活=0,分队=2}]" },{ "selector": "@a[tag=fatal_damage_died,scores={黄床存活=0,分队=3}]" },{ "selector": "@a[tag=fatal_damage_died,scores={绿床存活=0,分队=4}]" },{ "rawtext" : [{"translate":"text.tellraw.ingameinfo.final_kill"} ] } ] } } ] }
execute @e[type=armor_stand,name=main,scores={kill_tell_num=2}] ~~~ execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @a { "rawtext": [ { "translate": "%%5", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={分队=..1}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..2}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..3}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } }, { "selector": "@a[tag=fatal_damage_died]" }, {"translate":"text.tellraw.ingameinfo.kill_tell_num_2"}, { "translate": "%%5", "with": { "rawtext": [ { "selector": "@s[scores={分队=..1}]"}, { "selector": "@s[scores={分队=..2}]"}, { "selector": "@s[scores={分队=..3}]"}, { "selector": "@s[scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } },{ "selector": "@s" }, { "translate": "%%2", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={红床存活=0,分队=1}]" }, { "selector": "@a[tag=fatal_damage_died,scores={蓝床存活=0,分队=2}]" },{ "selector": "@a[tag=fatal_damage_died,scores={黄床存活=0,分队=3}]" },{ "selector": "@a[tag=fatal_damage_died,scores={绿床存活=0,分队=4}]" },{ "rawtext" : [{"translate":"text.tellraw.ingameinfo.final_kill"} ] } ] } } ] }
execute @e[type=armor_stand,name=main,scores={kill_tell_num=3}] ~~~ execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @a { "rawtext": [ { "translate": "%%5", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={分队=..1}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..2}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..3}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } }, { "selector": "@a[tag=fatal_damage_died]" }, {"translate":"text.tellraw.ingameinfo.kill_tell_num_3"}, { "translate": "%%5", "with": { "rawtext": [ { "selector": "@s[scores={分队=..1}]"}, { "selector": "@s[scores={分队=..2}]"}, { "selector": "@s[scores={分队=..3}]"}, { "selector": "@s[scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } },{ "selector": "@s" }, { "translate": "%%2", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={红床存活=0,分队=1}]" }, { "selector": "@a[tag=fatal_damage_died,scores={蓝床存活=0,分队=2}]" },{ "selector": "@a[tag=fatal_damage_died,scores={黄床存活=0,分队=3}]" },{ "selector": "@a[tag=fatal_damage_died,scores={绿床存活=0,分队=4}]" },{ "rawtext" : [{"translate":"text.tellraw.ingameinfo.final_kill"} ] } ] } } ] }
execute @e[type=armor_stand,name=main,scores={kill_tell_num=4}] ~~~ execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @a { "rawtext": [ { "translate": "%%5", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={分队=..1}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..2}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..3}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } }, { "selector": "@a[tag=fatal_damage_died]" }, {"translate":"text.tellraw.ingameinfo.kill_tell_num_4"}, { "translate": "%%5", "with": { "rawtext": [ { "selector": "@s[scores={分队=..1}]"}, { "selector": "@s[scores={分队=..2}]"}, { "selector": "@s[scores={分队=..3}]"}, { "selector": "@s[scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } },{ "selector": "@s" }, { "translate": "%%2", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={红床存活=0,分队=1}]" }, { "selector": "@a[tag=fatal_damage_died,scores={蓝床存活=0,分队=2}]" },{ "selector": "@a[tag=fatal_damage_died,scores={黄床存活=0,分队=3}]" },{ "selector": "@a[tag=fatal_damage_died,scores={绿床存活=0,分队=4}]" },{ "rawtext" : [{"translate":"text.tellraw.ingameinfo.final_kill"} ] } ] } } ] }
execute @e[type=armor_stand,name=main,scores={kill_tell_num=5}] ~~~ execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @a { "rawtext": [ { "translate": "%%5", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={分队=..1}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..2}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..3}]"}, { "selector": "@a[tag=fatal_damage_died,scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } }, { "selector": "@a[tag=fatal_damage_died]" }, {"translate":"text.tellraw.ingameinfo.kill_tell_num_5"}, { "translate": "%%5", "with": { "rawtext": [ { "selector": "@s[scores={分队=..1}]"}, { "selector": "@s[scores={分队=..2}]"}, { "selector": "@s[scores={分队=..3}]"}, { "selector": "@s[scores={分队=..4}]"}, { "text": "§c" }, { "text": "§b" }, { "text": "§e" }, { "text": "§a" } ] } },{ "selector": "@s" }, { "translate": "%%2", "with": { "rawtext": [ { "selector": "@a[tag=fatal_damage_died,scores={红床存活=0,分队=1}]" }, { "selector": "@a[tag=fatal_damage_died,scores={蓝床存活=0,分队=2}]" },{ "selector": "@a[tag=fatal_damage_died,scores={黄床存活=0,分队=3}]" },{ "selector": "@a[tag=fatal_damage_died,scores={绿床存活=0,分队=4}]" },{ "rawtext" : [{"translate":"text.tellraw.ingameinfo.final_kill"} ] } ] } } ] }
execute @e[type=armor_stand,name=main,scores={gameSTART=1}] ~~~ scoreboard players add @a[tag=fatal_damage_died] 总死亡数 1
# *
scoreboard players operation @a[tag=fatal_damage_died] xp_cache = @a[tag=fatal_damage_died] own_xp
scoreboard players operation @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] xp_cache = @a[tag=fatal_damage_died] xp_cache
scoreboard players operation @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] own_xp += @a[tag=fatal_damage_died] xp_cache
scoreboard players operation @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] got_xp = @a[tag=fatal_damage_died] xp_cache
# This is used for the tellraw below
execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ function api/add_xp_by_scoreboard_xp_cache
# DEBUG xp_cache !!!!!!
execute @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] ~~~ tellraw @s { "rawtext" : [{"translate":"text.tellraw.ingameinfo.get_xplevel_kill","with":{"rawtext":[{"score":{"name":"@s","objective":"got_xp"}}]}} ] }
scoreboard players add @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] 击杀数 1
scoreboard players add @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] 总击杀数 1
tag @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] add get.xp.kill
tag @a[tag=!fatal_damage_died,scores={fatal_damage_uid=0}] add get.coin.kill
# 隐身失效
execute @s[scores={invisible_time=1..}] ~~~ scoreboard players set @s invisible_time 0
execute @s[scores={invisible_time=1..}] ~~~ effect @s invisibility 0 3 true
# *
function get_xp_and_coin
scoreboard players reset * got_xp
scoreboard players reset * xp_cache
tag * remove fatal_damage_died
scoreboard players reset * fatal_damage_uid
scoreboard players reset * damage_uid.cache
